---
title: "Stack Overflow Analysis"
author: ""
date: "11 October, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 2016 Stack Overflow Survey data analysis

Correlation Calculation with different varialbes with "salary_midpoint":

```{r, echo=FALSE}
summary(Stack[,"gender"])

#fixed gender
Stack[,"gender2"] <- NA
for (i in 1:nrow(Stack)){
  if (Stack[i,"gender"] == "Female") Stack[i,"gender2"] <- "Female"
  if (Stack[i,"gender"] == "Male") Stack[i,"gender2"] <- "Male"
}

library(ggplot2)
#Number of female/male
summary(Stack[,"gender2"] == "Female") #3202 female
summary(Stack[,"gender2"] == "Male") #51388 male

# Salary by gender
ggplot(data=Stack) + geom_boxplot(aes(gender2, salary_midpoint))

# T-test on gender and salary
t.test(Stack[Stack[,"gender2"]=="Female", "salary_midpoint"], Stack[Stack[,"gender2"]=="Male", "salary_midpoint"], alternative = "two.sided")

# Correlation test among different variables with "salary_midpoint"
cor.test(stack[, "salary_midpoint"], stack[, "age_midpoint"])
cor.test(stack[, "salary_midpoint"], stack[, "programming_ability"])
cor.test(stack[, "salary_midpoint"], stack[, "experience_midpoint"])
cor.test(stack[, "salary_midpoint"], stack[, "big_mac_index"])

lm2 <- lm(salary_midpoint~ experience_midpoint + gender2 + big_mac_index + age_midpoint + programming_ability, data = Stack)
summary(lm2)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
